# Generated by Django 4.2.4 on 2023-08-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('course', models.IntegerField()),
                ('instrument', models.CharField(choices=[('g', 'Guitar'), ('p', 'Piano'), ('r', 'Recorder'), ('t', 'Trumpet')], max_length=60)),
                ('performance', models.IntegerField()),
                ('paid_for_studies', models.BooleanField(default=False)),
            ],
        ),
    ]
